import "./commands/commands";
import "./commands/ctCommandParser";
import "./commands/guildChatCommandParser";
import "./commands/privateMessageCommandParser";
import "./reactors/averageCharacterReactor";
import "./reactors/averageWordReactor";
import "./reactors/reactors"
import "./collector";
import "./utils/commons";
import "./utils/errorHandling";
import "./utils/guildChatEvent";