import "./commands/commands";
import "./commands/ctCommandParser";
import "./commands/guildChatCommandParser";
import "./reactors/averageWordReactor";
import "./reactors/reactors"
import "./collector";
import "./commons";
import "./errorHandling";
import "./guildChatEvent";